"""Phase 9: Streamlit chat UI (architecture §3, PRD §6).

Run from the project root:  streamlit run src/app/main.py

Chat history lives only in st.session_state (memory, per browser tab) and holds
the redacted question, never the raw input. Nothing is written to disk. The last
25 exchanges are passed to the pipeline as context for follow-up questions.
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.rag.context import HISTORY_TURNS  # noqa: E402
from src.rag.generate import generator_label  # noqa: E402
from src.rag.pipeline import Answer, ask  # noqa: E402

WELCOME = (
    "Hi! Ask me factual questions about five HDFC Mutual Fund schemes: expense "
    "ratio, exit load, minimum SIP, riskometer, benchmark, fund size, NAV or fund "
    "managers."
)
FACTS_ONLY_NOTE = "Facts-only. No investment advice."
DISCLAIMER = (
    "Facts-only answers from public scheme pages. This is not investment "
    "advice. Mutual fund investments are subject to market risks. Read all "
    "scheme-related documents carefully."
)
# PRD §14 says to use the three that retrieve most reliably after the first eval;
# all three are retrieved at rank 1 from the Groww corpus (docs/eval_notes.md).
# The ELSS lock-in example was dropped: Groww's pages do not state it.
EXAMPLES = [
    "What is the expense ratio of HDFC Large Cap Fund Direct Growth?",
    "What is the exit load on HDFC Small Cap Fund Direct Growth?",
    "What is the minimum SIP amount for HDFC Balanced Advantage Fund?",
]


@st.cache_resource(show_spinner="Loading the search index…")
def _warm_up() -> None:
    """Load the embedding model and Chroma collection once per server process."""
    from src.rag.retrieve import retrieve

    retrieve("warm up")


def render_answer(answer: Answer) -> None:
    payload = answer.payload
    if answer.pii_warning:
        st.warning(answer.pii_warning, icon="🔒")
    if answer.context_note:
        st.caption(f"↪ {answer.context_note}")
    if payload["refusal"]:
        st.info(payload["text"])
    else:
        st.markdown(payload["text"])
    if payload["source_url"]:
        st.markdown(f"**Source:** [{payload['source_url']}]({payload['source_url']})")
    if payload["last_updated_from_sources"]:
        st.caption(f"Last updated from sources: {payload['last_updated_from_sources']}")
    # The generator name and retrieved passages stay on `answer` for debugging
    # (scripts/debug_ask.py, scripts/debug_retrieve.py) but are not shown in chat.


def main() -> None:
    st.set_page_config(page_title="HDFC MF FAQ", page_icon="📄", layout="centered")
    st.title("Mutual Fund FAQ")
    st.success(FACTS_ONLY_NOTE, icon="ℹ️")

    with st.sidebar:
        st.subheader("About")
        st.write(DISCLAIMER)
        st.caption(
            "Schemes: HDFC Large Cap, Flexi Cap, ELSS Tax Saver, Small Cap and "
            "Balanced Advantage Fund (Direct Growth)."
        )
        st.caption(f"Answers generated by: {generator_label()}.")
        st.caption(
            f"Follow-up questions use the last {HISTORY_TURNS} exchanges of this chat "
            "as context (kept only in this browser session)."
        )
        if st.button("Clear chat"):
            st.session_state.history = []

    _warm_up()
    history: list[tuple[str, Answer]] = st.session_state.setdefault("history", [])

    with st.chat_message("assistant"):
        st.write(WELCOME)
        st.caption("Try an example:")
        for i, example in enumerate(EXAMPLES):
            if st.button(example, key=f"example-{i}", use_container_width=True):
                st.session_state.pending = example

    for question, answer in history:
        with st.chat_message("user"):
            st.write(question)
        with st.chat_message("assistant"):
            render_answer(answer)

    typed = st.chat_input("Ask about an HDFC scheme…")
    question = typed or st.session_state.pop("pending", None)
    if question:
        # Last HISTORY_TURNS exchanges (redacted questions + answer texts) as context
        # for follow-ups; session memory only.
        turns = [(q, a.payload["text"]) for q, a in history][-HISTORY_TURNS:]
        with st.spinner("Looking it up…"):
            answer = ask(question, turns)
        # Store and show only the redacted question; the raw input is dropped here.
        history.append((answer.redacted_query, answer))
        with st.chat_message("user"):
            st.write(answer.redacted_query)
        with st.chat_message("assistant"):
            render_answer(answer)

    st.divider()
    st.caption(DISCLAIMER)


main()
