"""Phase 10: write docs/sample_qa.md from real pipeline output (nothing hand-written).

Run from the project root after ingest:  python scripts/make_sample_qa.py
Uses whichever generator is active (Claude, Groq or the extractive fallback).
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.rag.generate import generator_label, generator_mode  # noqa: E402
from src.rag.pipeline import ask  # noqa: E402

OUT = PROJECT_ROOT / "docs" / "sample_qa.md"

QUESTIONS = [
    "What is the expense ratio of HDFC Large Cap Fund Direct Growth?",
    "What is the exit load on HDFC Small Cap Fund Direct Growth?",
    "What is the minimum SIP amount for HDFC ELSS Tax Saver?",
    "What is the fund size of HDFC Small Cap Fund?",
    "Who are the fund managers of HDFC Flexi Cap Fund?",
    "How do I download my capital gains statement?",
    "Which mutual funds can you access?",
    "Should I buy HDFC Small Cap Fund?",
    "Which fund had better returns, HDFC Flexi Cap or HDFC Large Cap?",
    "My PAN is ABCDE1234F. What is the lock-in for HDFC ELSS Tax Saver?",
]


def main() -> None:
    mode = generator_mode()
    generator = generator_label()
    lines = [
        "# Sample Q&A",
        "",
        f"Generated by `scripts/make_sample_qa.py` on {date.today().isoformat()} from the "
        f"live pipeline (guards → retrieval → generation → assembly). Generator: {generator}.",
        "Questions are shown as the pipeline stored them, so personal details appear redacted.",
        "",
    ]
    for i, question in enumerate(QUESTIONS, 1):
        answer = ask(question)
        p = answer.payload
        kind = f"Refusal ({p['refusal_reason']})" if p["refusal"] else "Answer"
        lines += [f"## {i}. {answer.redacted_query}", ""]
        if answer.pii_warning:
            lines += [f"> ⚠️ {answer.pii_warning}", ""]
        source = f"<{p['source_url']}>" if p["source_url"] else "none (fixed reply, not a fact from one page)"
        lines += [f"**{kind}:** {p['text']}", "", f"**Source:** {source}", ""]
        if p["last_updated_from_sources"]:
            lines += [f"**Last updated from sources:** {p['last_updated_from_sources']}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(QUESTIONS)} Q&As to {OUT} (generator: {mode})")


if __name__ == "__main__":
    main()
