"""Write docs/sample_qa.md from real pipeline output (nothing hand-written).

At least two examples per intent (PRD §6) plus every PRD §8 edge case, each shown in
the PRD §7 template: answer, source label + link, "Last updated from sources".
Run from the project root after ingest:  python scripts/make_sample_qa.py
Uses whichever generator is active (Claude, Groq or the extractive fallback).
"""

from __future__ import annotations

import sys
import time
from datetime import date
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.ingest.official import human_date  # noqa: E402
from src.rag.generate import generator_label, generator_mode  # noqa: E402
from src.rag.pipeline import ask  # noqa: E402

OUT = PROJECT_ROOT / "docs" / "sample_qa.md"

SECTIONS: list[tuple[str, list[str]]] = [
    ("Facts (the seven question types)", [
        "What is the expense ratio of HDFC ELSS Tax Saver Direct Growth?",
        "What is the exit load on HDFC Small Cap Fund?",
        "What is the minimum SIP amount for HDFC Balanced Advantage Fund?",
        "How long is the HDFC ELSS Tax Saver lock-in?",
        "What is the riskometer level of HDFC Large Cap Fund?",
        "What is the benchmark of HDFC Flexi Cap Fund?",
        "How do I download my capital gains statement?",
    ]),
    ("Facts kept by Addendum A1", [
        "What is the NAV of HDFC Small Cap Fund Direct Growth?",
        "Can you give me the holdings analysis of HDFC Balanced Advantage Fund?",
    ]),
    ("Advice (refused, with an offer and an education link)", [
        "Should I buy HDFC Small Cap now?",
        "Which is better for me, Flexi Cap or Large Cap?",
        "What's the exit load and should I exit now?",
    ]),
    ("Performance (refused, with the factsheet link)", [
        "What were HDFC Flexi Cap's 5-year returns?",
        "Has Balanced Advantage beaten its benchmark?",
    ]),
    ("Out of scope and non-mutual-fund", [
        "What's the exit load on SBI Small Cap?",
        "How do I apply for an HDFC Bank credit card?",
    ]),
    ("PII (blocked; nothing is sent or stored)", [
        "My PAN is ABCDE1234F, show my ELSS lock-in date",
        "OTP is 482913, why isn't my statement coming?",
    ]),
    ("PRD §8 edge cases", [
        "Exit load on HDFC Top 100?",  # scheme rename
        "What's the expense ratio of HDFC Flexi Cap?",  # Direct vs Regular
        "What is the expense ratio of HDFC Flexi Cap regular plan?",  # Regular -> out of scope
        "Exit loads of Small Cap vs Flexi Cap?",  # factual comparison
        "Which has lower risk, so should I pick it?",  # merit comparison
        "HDFC Mid Cap Opportunities exit load?",  # scheme not in corpus
        "hdfc smallcap exit load",  # partial name
        "What is the expense ratio of HDFC cap fund?",  # two or more matches -> chips
        "How do I get my CAS?",  # statement download
    ]),
]


def main() -> None:
    mode = generator_mode()
    lines = [
        "# Sample Q&A",
        "",
        f"Generated by `scripts/make_sample_qa.py` on {date.today():%d %b %Y} from the live "
        f"pipeline (PII check → guards → retrieval → generation → validator → template). "
        f"Generator: {generator_label()}.",
        "Questions are shown as the pipeline stored them, so personal details appear redacted "
        "(a blocked PII message is never stored; it is shown redacted here only).",
        "Conflicting sources (PRD §8) are handled in retrieval (newest document first) and "
        "have no single question to show.",
        "",
    ]
    n = 0
    for title, questions in SECTIONS:
        lines += [f"## {title}", ""]
        for question in questions:
            n += 1
            answer = ask(question)
            if answer.payload["refusal_reason"] == "error":  # e.g. a Groq rate limit
                time.sleep(65)
                answer = ask(question)
            p = answer.payload
            kind = f"Refusal ({p['refusal_reason']})" if p["refusal"] else "Answer"
            lines += [f"### {n}. {answer.redacted_query}", ""]
            if answer.context_note:
                lines += [f"> ↪ {answer.context_note}", ""]
            lines += [f"**{kind}:** {p['text']}", ""]
            if p.get("chips"):
                lines += ["**Chips:** " + " · ".join(p["chips"]), ""]
            if p["source_url"]:
                lines += [f"Source: [{p.get('source_label') or p['source_url']}]({p['source_url']})", ""]
            if p["last_updated_from_sources"]:
                lines += [f"Last updated from sources: {human_date(p['last_updated_from_sources'])}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {n} Q&As to {OUT} (generator: {mode})")


if __name__ == "__main__":
    main()
